version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.0
    working_directory: ~/repo
    steps:
      - run:
          name: install graphviz
          command: |
            sudo apt-get update
            sudo apt-get install -y graphviz
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -U pip poetry
            poetry install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "poetry.lock" }}
      - run:
          name: run linters
          command: |
            . venv/bin/activate
            flake8 residuated_binars
            pylint residuated_binars
      - run:
          name: run type checks
          command: |
            . venv/bin/activate
            mypy residuated_binars
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov-report xml residuated_binars tests
      - run:
          name: upload data to codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
      - store_test_results:
          path: test-results

workflows:
  main:
    jobs:
      - build-and-test
